// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mswnlbuxhnxfwnrtdlcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zd25sYnV4aG54ZnducnRkbGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTEzOTYsImV4cCI6MjA2MTUyNzM5Nn0.5gCkgvks7USyJx6HPIVteJmldTOHIaKZZmq0At4C-VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'broDrobe-auth-token'
  }
});
